# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Triviac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Triviac
pod 'Alamofire'
pod 'SnapKit'
pod 'HTMLEntities', :git => 'https://github.com/IBM-Swift/swift-html-entities.git'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'AMTabView'
pod 'SlidingNumberView'

end
